version: '3.8'
services:
  db:
    container_name: summonertracker-db
    image: postgres:13.12-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: summonertracker-api
    ports:
      - "5432:5432"